# wrangler.toml
name = "gemini-proxy-panel1"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "3a2a1fe99c334db298f176432af30316"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "3a2a1fe99c334db298f176432af30316"
